### ISSUE TITLE
Branch development/apar2plusbpar: duplicate function for enabling apar or bpar with prevalence of deprecated variables

### ISSUE THREAD

**Issue by jregana** [stellaGK/stella#130]
The variables fapar and fbpar, in case they are set in the input file, are marked as deprecated according to a warning message in the output file, but they take precedence over the newer variables include_apar and include_bpar. If fapar (or fbpar) have null values, the code sets include_apar (or include_bpar) to .false.. Conversely, if they have finite values, the code sets include_apar (or include_bpar) to .true., no matter the value of include_apar or include_bpar had on the input.

I imagine that fapar and bpar should be removed or, if they are kept, they should be considered merely as initialization values for the fields they refer to, similar to how I believe fphi functions with respect to the electrostatic potential.

In the following screenshot, fapar=1 was set in the input:

<img width="722" alt="z55QDL0wcChnqRD0" src="https://github.com/stellaGK/stella/assets/40162674/f5933956-e97d-44d1-9060-38deea42ea5f">

In the following screenshot, fapar=0 was set in the input:

<img width="548" alt="Xt7S0liR23J1Frn5" src="https://github.com/stellaGK/stella/assets/40162674/7b1193e6-99fd-4cc7-8449-484e69f18c91">

**Comment by mrhardman** [comment]
@mabarnes Do we want to remove `fapar` `fbpar` completely? Happy to make the changes needed if so.

**Comment by jregana** [comment]
Yes, [28ccf39](https://github.com/stellaGK/stella/commit/28ccf39405810c4a007c1468e044e0f300a93026) fixes the issue. Thanks!
