### ISSUE TITLE
Definition of vnew_ref

### ISSUE THREAD

**Issue by mrhardman** [stellaGK/stella#134]
Looking through the source, the normalised collision frequency `vnew_ref` does not appear to be defined. It would be helpful for the original authors of this feature to document the correct units, perhaps at the line below.

https://github.com/stellaGK/stella/blob/e1da75cc24e556dfac9eba7a0759124bab905046/physics_parameters.f90#L44

**Comment by mabarnes** [comment]
I have just pushed a commit where the documentation for vnew_ref was copied from its original location, which was in the obvious file euterpe_interface.f90 :)
