### ISSUE TITLE
time_advance: Resetting the timestep size code_dt after implicitly advancing doesn't re-do the implicit advance on that timestep

### ISSUE THREAD

**Issue by rd1042** [stellaGK/stella#33]
advance_stella in the master branch has the following:

`    if (mod(istep,2)==1 .or. .not.flip_flop) then
       ! advance the explicit parts of the GKE
       call advance_explicit (gnew)

       ! enforce periodicity for zonal mode
!    if (zonal_mode(1)) gnew(1,:,-nzgrid,:) = gnew(1,:,nzgrid,:)

       ! use operator splitting to separately evolve
       ! all terms treated implicitly
       if (.not.fully_explicit) call advance_implicit (istep, phi, apar, gnew)
    else
       if (.not.fully_explicit) call advance_implicit (istep, phi, apar, gnew)
       call advance_explicit (gnew)
    end if` 

Adjusting timestep size code_dt for numerical stability is handled in advance_explicit; however, if advance_explicit is called after advance_implicit (which always occurs if flip_flop = .false. , and every other timestep if flip_flop = .true.), the implicit advance is not re-performed with the smaller code_dt. This means that the timestep on which code_dt resets is inconsistent (although in subsequent timesteps advance_implicit uses the reduced code_dt).

Proposed fix: Move the reset_dt logic into the advance_stella subroutuine; try taking a full timestep, and then check the flag restart_time_step . If restart_time_step==.true. , throw away the changes and repeat the whole timestep with the reduced code_dt. I've implemented something like this in the branch feature/nisl_leapfrog_nonlinearity , so will do same in master.

**Comment by DenSto** [comment]
Ah, good catch!  You should do the fix and then make a pull request.

**Comment by DenSto** [comment]
Has this been fixed in a branch? If so, can a pull request be made?

**Comment by DenSto** [comment]
It should be noted that for the default case, flip_flop = .false., advance_explicit is actually performed first, so for the typically use case this shouldn't have been a problem.

**Comment by rd1042** [comment]
I've written a fix, but haven't yet tested it (need to update my compiler due to array length issue). I'll try and get the PR in today/tomorrow

**Comment by rd1042** [comment]
I've written a fix for this (branch bugfix/reset_dt_consistently-new ), but will run some tests with a nonlinear simulation and some write statements to ensure it behaves as designed.
