### ISSUE TITLE
Any interest in omega in netcdf output?

### ISSUE THREAD

**Issue by d7919** [stellaGK/stella#38]
I've been doing some linear comparisons with GS2 for testing the electromagnetic terms and to aid this I added the omega data to the netcdf output. I'm happy to make a PR for this if it is something useful for general use, but thought I'd check first in case it doesn't fit with common use.

**Comment by d7919** [comment]
I've pushed the code to https://github.com/d7919/stella/tree/feature/omega_in_diagnostics in case of interest.

**Comment by DenSto** [comment]
I think this would be useful, since the .omega ascii files are already pretty unwieldy, so having them in the netcdf file can only be a good thing. Go ahead and submit the pull request.
