### ISSUE TITLE
Missing broadcast of species_type_switch?

### ISSUE THREAD

**Issue by d7919** [stellaGK/stella#43]
The species type input is not broadcast and may be overridden on just proc0. Perhaps this is broadcast elsewhere - might be worth a comment to note this if this is the case. 
https://github.com/stellaGK/stella/blob/14a4c9047c55c114f8bfa3a85410df4339b94759/species.f90#L159-L191

**Comment by DenSto** [comment]
You're right that it's not broadcasted.  I believe it's only proc0 that uses this switch, though.  Perhaps it'd be a good idea to broadcast it anyway, in order to avoid 'gotcha's' in the future.

**Comment by d7919** [comment]
> You're right that it's not broadcasted. I believe it's only proc0 that uses this switch, though. Perhaps it'd be a good idea to broadcast it anyway, in order to avoid 'gotcha's' in the future.

That makes sense, otherwise I expect this would have caused problems for any non-default use. I agree that broadcasting anyway is probably a good idea to avoid potential issues in the future.

**Comment by DenSto** [comment]
Pushed.
