### ISSUE TITLE
mpi_win_free error due to apparent bug in finish_sources subroutine

### ISSUE THREAD

**Issue by mabarnes** [stellaGK/stella#52]
When running on 48 cores of a single node on Marconi, standard nonlinear simulations run from a noise initial condition make it to the end of all time steps but crash during an mpi_win_free call in the finish_sources subroutine.  The error message is:

Fatal error in MPI_Win_free: Invalid MPI_Win, error stack:
MPI_Win_free(147): MPI_Win_free(win=0x16ab1c0) failed
MPI_Win_free(75).: Invalid MPI_Win

**Comment by DenSto** [comment]
Good catch. I'll get to it.
