### ISSUE TITLE
NetCDF errors occur when fphi=0

### ISSUE THREAD

**Issue by rd1042** [stellaGK/stella#60]
If a simulation uses fphi=0, errors occur when writing to the .out.nc file. From the .error file we see the following errors:

ERROR in netcdf_error: NetCDF: Variable not found in varid:        0, ncid:    65536
ERROR: NetCDF: Variable not found

The reason for this is that, within stella_io, the IDs for phi-related diagnostics (e.g. phi2_id , phi_vs_t_id) are only set if fphi != 0. However, diagnose_stella will try to write diagnostics like phi2 even if fphi=0; this causes an error because the ID is unset. (NB setting fphi=0 is a rare occurrence.)

Proposed solution: either (1) Always set the stella_io IDs, even if fphi=0, or (2) only try to write phi-related diagnostics if fphi=1. (1) seems more consistent with the rest of stella (we still allocate and set phi if fphi=0 for example, and apar is allocated, set and written to plaintext diagnostics even if fapar=0.)

**Comment by ZedThree** [comment]
Another solution: use my [neasy-f](https://github.com/PlasmaFAIR/neasy-f) wrapper which would remove the need to keep the IDs around at all. I have a PR adding this to GS2 and managed to remove ~1200 lines.

The cost is that it relies on NetCDF-4 which is backed by HDF5. This has an issue where reading files while they're being written can break things.
On the plus side, this does mean it's possible to enable compression, giving smaller file sizes.

I'm happy to make a PR for this if it sounds useful.

**Comment by DenSto** [comment]
That does sound tempting. Does neasy-f have the capability of reopening netcdf files and appending information to the arrays at appropriate locations? Stella has this capability, and perhaps also GS2, but that I'm not sure.

**Comment by DenSto** [comment]
OK! Submit a pull request and I can check it out
