### ISSUE TITLE
cmake build for master branch fails on Marconi

### ISSUE THREAD

**Issue by mabarnes** [stellaGK/stella#84]
When trying to use cmake with the latest version of the master branch, I get the following error message:
CMake Error at externals/neasyf/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.20 or higher is required.  You are running version 3.18.2

As far as I can see, the most recent version of CMake available on Marconi is 3.18.2.  Is there a workaround for this?

**Comment by ZedThree** [comment]
Easiest thing probably is to install the latest version of cmake: `pip install --user cmake`

This puts it in `~/.local/bin`, so you might need to add that to your `PATH`

If that doesn't work, I can check to see if neasyf will work with 3.18

**Comment by mabarnes** [comment]
Any idea how to get access to pip on Marconi?  This is not available by default and not sure what module (if any) I'd need to load to get it...

**Comment by ZedThree** [comment]
It should be in the python module. I don't think you need any others, but I
can check

**Comment by DenSto** [comment]
> 

Python3 should come with it. Something like 'python3 -m pip install --user cmake' should work
