### ISSUE TITLE
Namelist documentation from database

### ISSUE THREAD

**Issue by DenSto** [stellaGK/stella#95]
I know GS2 has a very sophisticated way of autogenerating the namelist documentation on the website. I don't think we need something so complex... maybe we can store all the namelist info in a JSON or XML which can then be translated to HTML on the documentation website somehow? Peter, do you know of any standard ways of doing this? I don't mind writing up the JSON/XML file.

**Comment by ZedThree** [comment]
The simplest thing to do is probably to add a markdown file under [docs/pages/user_manual](https://github.com/stellaGK/stella/tree/master/docs/pages/user_manual).

Then dead simple formatting:

```markdown
# namelist name
- *variable*: description
```

which will render like:

# namelist name
- *variable*: description

---

Or fancier using [tables](https://python-markdown.github.io/extensions/tables/)

```markdown
# namelist name

Variable | Type | Default | Description
-------- | ---- | ------- | -----------
*variable* | integer | 1 | description
```
which will render like:

# namelist name

Variable | Type | Default | Description
------- | ---- | ------- | -----------
*variable* | integer | 1 | description

---

At some point I do plan on adding the ability to autogenerate namelist docs, but I am spread quite thin!

**Comment by DenSto** [comment]
OK. I've started [playing around with it here](https://stellagk.github.io/stella/page/user_manual/namelists.html). My only question is how to have so that each row has alternating light/dark background, much like what the GS2 page. Is there an easy way to do that?

**Comment by ZedThree** [comment]
Yep, add `md_extensions: ford.md_striped_table` to https://github.com/stellaGK/stella/blob/2dacec1c409b2b199b248245178ac0b6c56544d7/docs/stella_docs.md?plain=1#L25-L26

```diff
  md_extensions: markdown.extensions.toc
+                ford.md_striped_table
  ---
```

**Comment by DenSto** [comment]
That's the ticket! It looks much better. I'll slowly fill in the page now.

**Comment by DenSto** [comment]
OK. I filled in most of the namelist information. One thing I did do was write a short script that's called with `make docs` that generates the namelist markdown from individual namelist files. Otherwise a single markdown file would be too unwieldy. I may have done it in an inefficient way, but it seems to work.
